services:
  # Nginx Reverse Proxy
  rp:
    image: nginx:1.29.1
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./nginx:/etc/nginx:Z
    depends_on:
      - th
    restart: unless-stopped

  th:
    build:
      context: .
    volumes:
      - db:/app/data
      - logs:/app/logs
    restart: unless-stopped

volumes:
  db:
    driver: local
  logs:
    driver: local
